name: Publish on Azure NPM registry
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: ponicode/azure-devops-npm-action@master
          with:
              organisation: capexdev
              project: CPXDEV
              registry: https://pkgs.dev.azure.com/capexdev/CPXDEV/_packaging/github-demo/npm/registry/
              user: capexdev
              password: ${{ secrets.AZURE_TOKEN }}
              email: andra.radu@capex.tech
              scope: ponicode
        - run: cp `pwd`/.npmrc ~ # We need the .npmrc file in the $HOME directory
        - name: Install dependencies
          run: cd myExpressApp && npm install
        - name: Build
          run: cd myExpressApp && npm run build
        - name: Publish to Azure
          run: cd myExpressApp && npm publish
