name: Publish on Azure NPM registry
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: dummy-andra/azure-devops-npm-action-custom@main
          with:
              organisation: capexdev
              project: CPXDEV
              registry: github-demo
              user: capexdev
              password: ${{ secrets.AZURE_TOKEN }}
              email: andra.radu@capex.tech
        - run: cp `pwd`/.npmrc ~
        - name: Install dependencies
          run: cd myExpressApp && npm cache clean && sudo apt-get install build-essential && npm install
        - name: Publish to Azure
          run: cd myExpressApp && cat ~/.npmrc && npm publish
