name: CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: innerspacetrainings/azure-npm-publish@master
        with:
          package-dir: 'myExpressApp'
          npm-email: andra.radu@capex.tech'
          organization: 'CPXDEV'
          feed: 'github-demo'
          username: 'anything-for-the-logs'
          base64-token: ${{ secrets.AZURE_TOKEN }}
