name: Publish on Azure NPM registry
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: ponicode/azure-devops-npm-action@master
          with:
              organisation: capexdev
              project: CPXDEV
              registry: https://pkgs.dev.azure.com/capexdev/CPXDEV/_packaging/github-demo/npm/registry/
              user: capexdev
              password: ${{ secrets.AZURE_TOKEN }}
              email: andra.radu@capex.tech
              scope: ponicode
        - run: pwd; ls -lat; mv `pwd`/.npmrc ~; cat ~/.npmrc
        - run: cd ~; pwd; ls -lat;
        - name: Install dependencies
          run: pwd; ls -lat; cd myExpressApp && npm install
        - name: Publish to Azure
          run: pwd; ls -lat; cd myExpressApp && npm publish
